#!/usr/bin/env python
# - coding: utf-8 -
# email css linter

import os
import sys
from emailipy import lint_css


if __name__ == "__main__":
    args = sys.argv[1:]

    if args:
        if not os.path.exists(args[0]):
            print "emailipy-lint <file> -- need to specify a valid file"
            sys.exit()

        css= ""
        with open(args[0], "r") as f:
            css = f.read()

        issues = lint_css(css)
        if issues:
            for issue in issues:
                print issue
        else:
            print "No issues found."
    else:
        print "emailipy-lint <file>"
