#!/usr/bin/env python
# - coding: utf-8 -
# css inliner

import os
import sys
from emailipy import inline_css


if __name__ == "__main__":
    args = sys.argv[1:]

    if len(args) >= 2:
        files = {}
        for i, extension in enumerate(["html", "css"]):
            if not os.path.exists(args[i]):
                print "emailipy-inline <html_file> <css_file> -- need to specify a valid {} file".format(extension)
                sys.exit()
            with open(args[i]) as f:
                files[extension] = f.read()

        include_invalid = len(args) >= 3 and "--allow_invalid_css" in args
        html = inline_css(*files.values(), include_invalid=include_invalid)
        print html
    else:
        print "emailipy-inline <html_file> <css_file>"
        print "--allow_invalid_css\t\tAllows css that doesn't lint."
